### ISSUE TITLE
Part 2: Crew Member -Update

### ISSUE THREAD

**Issue by rtate2** [nss-evening-cohort-10/nutshell-panam-airlines#10]
# User Story
As a user, I should be able to edit a crew member on the team.

# Acceptance Criteria
**GIVEN** the user is logged in and visits the Crew Member page
**WHEN** the user clicks the edit button on the crew member card
**THEN** a modal will pop up with pre-populated fields for the crew member

**WHEN** the save button is clicked
**THEN** the updated object is sent to firebase
**AND** the DOM is updated

# Dev Notes
* Create ` updateCrewMember(crewMemberId) => axios.put(crewMemberId, updatedCrewMember)` in `crewMemberData.js` file
* Create `editCrewMember` function in `crewMember.js` file that builds a `changedCrewMember` object to pass into `updateCrewMember();` when called from `crewMemberData.js`
* Within `editCrewMember` call `updateCrewMember();` and pass in the `changedCrewMember`
* Within `editCrewMember` call `createCrewCard();` to update the DOM
* Create event listener on the `Save Changes` button (of the editing modal) in `crewMember.js` file  this will call the 'editCrewMember`

**Comment by rtate2** [comment]
**Update button and example modal** 
<img width="815" alt="PanAm-Crew-Update-w:Modal" src="https://user-images.githubusercontent.com/54008854/68997802-06b36180-0870-11ea-9768-2bb1de27ce04.png">

**Comment by michaelclark2** [comment]
There should be an edit button on each individual crew member so that I can edit one of my chooseing.  Just in the same fashion the delete functionality will work.  When i click the edit button for the crew member, I should see a modal with a form that has been pre filled out with the crew members information, so that I can edit the info, then click a submit button that will update the crew member in firebase.
