### ISSUE TITLE
Plane Seed Data

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/nutshell-panam-airlines#25]
# User Story
As a developer I need some seed data to start coding.
# Dev Notes 
- Create a ra-planeSeedData branch
- Create `planes.json` file in `db` folder with planes seed data for firebase
- Import `planes.json` into firebase

# AC 
When I log into Firebase and see the data objects I imported

**Comment by rarceneaux** [comment]
```
{
  "plane1": {
    "team": " string teamA",
    "airport": "string BNA",
    "planeNum": "string w/ Numbers AB850",
    "modelType": "string w/ Number Boeing 737",
    "capacity": number 150,
  }
```

**Comment by michaelclark2** [comment]
This user story is incomplete.  Think about why you need this.  As a developer, you need seed data in order to start building your application.  then your acceptance criteria should be how you can tell when you have all the steps in place: what your collection is called in firebase, what your objects will look like (which you've done) and how many objects to create, and it seems other team members have included how to get the data from firebase in their seed data.  check with your team to see if that's what they all want to do
